### ISSUE TITLE
sugguestion

### ISSUE THREAD

**Issue by MCPEPIG** [Gamecrafter/Small-Plugins#4]
Can you add the phar files for each plugin in this repository?

**Comment by Gamecrafter** [comment]
I would upload everything, if I knew how!!! :( I might upload it on PocketMine anyways.

**Comment by MCPEPIG** [comment]
Maybe put the phar downloads here

**Comment by MCPEPIG** [comment]
Or in the readme

**Comment by Gamecrafter** [comment]
You have to upload the raw PHAR files.

**Comment by MCPEPIG** [comment]
Then do it

**Comment by Gamecrafter** [comment]
I don't know how. Do you know how?

**Comment by MCPEPIG** [comment]
Lemme see

**Comment by Gamecrafter** [comment]
So, do you know how?

**Comment by MCPEPIG** [comment]
Go to release

**Comment by Gamecrafter** [comment]
What???

**Comment by MCPEPIG** [comment]
Then create new release

**Comment by MCPEPIG** [comment]
The release tab at the top of the repo

**Comment by Gamecrafter** [comment]
I don't see it.

**Comment by MCPEPIG** [comment]
See the bar with the number of commits, branches, and contributers

**Comment by Gamecrafter** [comment]
Oh I see it now, I'll make a test repo to test it out first.

**Comment by MCPEPIG** [comment]
Ok

**Comment by Gamecrafter** [comment]
Nope, no use, I want it to look something like this: github.com/cybercube-hk/healthplus

**Comment by MCPEPIG** [comment]
Maybe just give us the download links

**Comment by Gamecrafter** [comment]
If I can't upload it then I can't give you the links.

**Comment by MCPEPIG** [comment]
No on dropbox or something

**Comment by Gamecrafter** [comment]
I don't use that. I'll find a way to upload it on here.

**Comment by Gamecrafter** [comment]
Okay, I uploaded the `.phar` plugins.
