### ISSUE TITLE
Idea... not issue

### ISSUE THREAD

**Issue by thedeibo** [Gamecrafter/Small-Plugins#8]
With every plugin, add a sort of "Readme" file, to explain what the plugins are, before people use it. That way people will know what it is, and will help them look for a plugin they want.

in short, description ;P

Hope it helps, TheDeibo

and if ur wondering why its in a issue... i just couldnt be bothered, and just dropped it here

**Comment by Gamecrafter** [comment]
Was planning to do that sooner or later, but after all, the code is more important! Will add some time this week.
