### ISSUE TITLE
permission nodes dont work

### ISSUE THREAD

**Issue by thedeibo** [Gamecrafter/Small-Plugins#9]
im using this as an example.
Server staff.
serverstaff.command.staff

I tried adding it to a group with Pureperms, and it came back with 
"Permission Node serverstaff.command.staff does NOT exist."

Hope it helps...

Idea:
1. If you allow all players by default to access some plugins like the Staff one, and the staff law. it might be easier
2. Try make the permissions to work.

( just another idea, you dont have to agree... and I hope you don't think of me being annoying... im just plainly debugging, or` finding faults for you.)
Otherwise, it all works great!
Hope also helps, 

TheDeibo
IGN: TheDeiboKnows

**Comment by Gamecrafter** [comment]
You should read the file `plugin.yml` carefully. You'll find interesting things there. The reason is because I haven't registered the nodes yet.
